##VARIABLES
paths = -I../inc
src = ../src
obj = ../obj
flags = -Wall -g
cc = g++
cmd = $(cc) -c $(flags) $(paths) $@.cpp -o $(obj)/$@.o


##CIBLES


Node:
	$(cmd)

WeightedNode:
	$(cmd)

Edge:
	$(cmd)

WeightedEdge:
	$(cmd)

DiGraph:
	$(cmd)

DirectableGraph:
	$(cmd)

PonderableGraph:
	$(cmd)

NamedColor:
	$(cmd)
