##VARIABLES
inc = ../inc
src = ../src
obj = ../obj
tmp = ../templates
paths = -I$(inc) -I$(tmp)
flags = -Wall -g
cc = g++
cmd = $(cc) -c $(flags) $(paths) $@.cpp -o $(obj)/$@.o


##CIBLES


GraphTypes:
	$(cmd)

Node:
	$(cmd)

WeightedNode:
	$(cmd)

Edge:
	$(cmd)

WeightedEdge:
	$(cmd)

BasicGraphException:
	$(cmd)

InvalidNodeID:
	$(cmd)

InvalidEdge:
	$(cmd)

InvalidOperation:
	$(cmd)

TopologyIterator:
	$(cmd)

DoubleNodeSetIterator:
	$(cmd)

BaseGraph:
	$(cmd)

DirectableGraph:
	$(cmd)

PonderableGraph:
	$(cmd)

NamedColor:
	$(cmd)

Visitor:
	$(cmd)

ColorizingVisitor:
	$(cmd)

TricolorBuilderVisitor:
	$(cmd)
