##VARIABLES
paths = -I../inc
src = ../src
obj = ../obj
flags = -Wall -g
cc = g++
cmd = $(cc) -c $(flags) $(paths) $@.cpp -o $(obj)/$@.o


##CIBLES


GraphTypes:
	$(cmd)

Node:
	$(cmd)

WeightedNode:
	$(cmd)

Edge:
	$(cmd)

WeightedEdge:
	$(cmd)

BasicGraphException:
	$(cmd)

InvalidNodeIDException:
	$(cmd)

TopologyIterator:
	$(cmd)

BaseGraph:
	$(cmd)

DirectableGraph:
	$(cmd)

PonderableGraph:
	$(cmd)

NamedColor:
	$(cmd)
